List<Map<String, dynamic>> countries = [
  {
    'countryCode': 1,
    'isoCountryCode': 'us',
    'countryName': 'United States',
    'countryNameNative': 'United States',
    'flagLink': 'https://flagcdn.com/w320/us.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 91,
    'isoCountryCode': 'in',
    'countryName': 'India',
    'countryNameNative': 'भारत',
    'flagLink': 'https://flagcdn.com/w320/in.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 44,
    'isoCountryCode': 'gb',
    'countryName': 'United Kingdom',
    'countryNameNative': 'United Kingdom',
    'flagLink': 'https://flagcdn.com/w320/gb.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 61,
    'isoCountryCode': 'au',
    'countryName': 'Australia',
    'countryNameNative': 'Australia',
    'flagLink': 'https://flagcdn.com/w320/au.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 9,
  },
  {
    'countryCode': 49,
    'isoCountryCode': 'de',
    'countryName': 'Germany',
    'countryNameNative': 'Deutschland',
    'flagLink': 'https://flagcdn.com/w320/de.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 11,
  },
  {
    'countryCode': 33,
    'isoCountryCode': 'fr',
    'countryName': 'France',
    'countryNameNative': 'France',
    'flagLink': 'https://flagcdn.com/w320/fr.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 9,
  },
  {
    'countryCode': 81,
    'isoCountryCode': 'jp',
    'countryName': 'Japan',
    'countryNameNative': '日本',
    'flagLink': 'https://flagcdn.com/w320/jp.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 86,
    'isoCountryCode': 'cn',
    'countryName': 'China',
    'countryNameNative': '中国',
    'flagLink': 'https://flagcdn.com/w320/cn.png',
    'minPhoneNumDigit': 11,
    'maxPhoneNumDigit': 11,
  },
  {
    'countryCode': 7,
    'isoCountryCode': 'ru',
    'countryName': 'Russia',
    'countryNameNative': 'Россия',
    'flagLink': 'https://flagcdn.com/w320/ru.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 55,
    'isoCountryCode': 'br',
    'countryName': 'Brazil',
    'countryNameNative': 'Brasil',
    'flagLink': 'https://flagcdn.com/w320/br.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 11,
  },
  {
    'countryCode': 27,
    'isoCountryCode': 'za',
    'countryName': 'South Africa',
    'countryNameNative': 'South Africa',
    'flagLink': 'https://flagcdn.com/w320/za.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 9,
  },
  {
    'countryCode': 34,
    'isoCountryCode': 'es',
    'countryName': 'Spain',
    'countryNameNative': 'España',
    'flagLink': 'https://flagcdn.com/w320/es.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 9,
  },
  {
    'countryCode': 39,
    'isoCountryCode': 'it',
    'countryName': 'Italy',
    'countryNameNative': 'Italia',
    'flagLink': 'https://flagcdn.com/w320/it.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 52,
    'isoCountryCode': 'mx',
    'countryName': 'Mexico',
    'countryNameNative': 'México',
    'flagLink': 'https://flagcdn.com/w320/mx.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 82,
    'isoCountryCode': 'kr',
    'countryName': 'South Korea',
    'countryNameNative': '대한민국',
    'flagLink': 'https://flagcdn.com/w320/kr.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 11,
  },
  {
    'countryCode': 62,
    'isoCountryCode': 'id',
    'countryName': 'Indonesia',
    'countryNameNative': 'Indonesia',
    'flagLink': 'https://flagcdn.com/w320/id.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 12,
  },
  {
    'countryCode': 60,
    'isoCountryCode': 'my',
    'countryName': 'Malaysia',
    'countryNameNative': 'Malaysia',
    'flagLink': 'https://flagcdn.com/w320/my.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 234,
    'isoCountryCode': 'ng',
    'countryName': 'Nigeria',
    'countryNameNative': 'Nigeria',
    'flagLink': 'https://flagcdn.com/w320/ng.png',
    'minPhoneNumDigit': 10,
    'maxPhoneNumDigit': 10,
  },
  {
    'countryCode': 66,
    'isoCountryCode': 'th',
    'countryName': 'Thailand',
    'countryNameNative': 'ประเทศไทย',
    'flagLink': 'https://flagcdn.com/w320/th.png',
    'minPhoneNumDigit': 9,
    'maxPhoneNumDigit': 10,
  }
];
